const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {randomUUID}=require('node:crypto');
const {openStore}=require('../tools/sqlite-tasks.cjs');const {createTask}=require('../api/_personal/task-model');const {createHandler}=require('../api/personal-tasks');const {COOKIE,sign}=require('../api/_cockpit/session');
function temporary(){return fs.mkdtempSync(path.join(os.tmpdir(),'heidewitzka-tasks-'));}
const password='temporary-test-password-32-characters';process.env.COCKPIT_PASSWORD=password;
function cookie(){const v=String(Date.now()+3600000)+'.'+'a'.repeat(32);return `${COOKIE}=${v}.${sign(v,password)}`;}
async function call(handler,method='GET',body,headers={}){const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.body=JSON.parse(v);}};await handler({method,body,headers:{host:'example.test',origin:'https://example.test','content-type':'application/json',cookie:cookie(),...headers}},res);return res;}
test('create, edit, complete, reopen, restart and idempotent creation',()=>{const dir=temporary();let store=openStore(dir);try{const id=randomUUID();const first=store.create({title:'Test only'},id);assert.equal(store.create({title:'Test only'},id).id,id);assert.equal(store.list().length,1);assert.throws(()=>store.create({title:'different'},id),{status:409});const changed=store.update(id,1,{title:'Changed',plannedDay:'2026-10-05',deadline:'2026-10-11',status:'done'});assert.equal(changed.version,2);assert.ok(changed.completedAt);assert.throws(()=>store.update(id,1,{title:'Stale'}),{status:409});store.close();store=openStore(dir);assert.equal(store.list()[0].title,'Changed');assert.equal(store.list()[0].deadline,'2026-10-11');assert.equal(store.update(id,2,{title:'Changed',status:'inbox'}).completedAt,null);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('validation rejects invalid dates, titles, statuses and unknown fields',()=>{for(const data of [{title:''},{title:'t',deadline:'2026-02-30'},{title:'t',status:'unknown'},{title:'t',durationMinutes:-1},{title:'t',secret:'bad'},{title:'t',labels:['']},{title:'t',plannedDay:'2026-2-4'}])assert.throws(()=>createTask(data),{status:400});});
test('API enforces authentication before availability and rejects foreign origins',async()=>{const unavailable=createHandler();assert.equal((await call(unavailable,'GET',null,{cookie:''})).statusCode,401);assert.equal((await call(unavailable)).statusCode,503);assert.equal((await call(unavailable,'POST',{}, {origin:'https://evil.test'})).statusCode,403);assert.equal((await call(unavailable,'GET',null,{cookie:cookie()+'bad'})).statusCode,401);});
test('API stores data, preserves conflict errors and rejects invalid request bodies',async()=>{const dir=temporary(),store=openStore(dir),handler=createHandler(store);try{const first=await call(handler,'POST',{id:randomUUID(),task:{title:'Test'}});assert.equal(first.statusCode,201);assert.equal((await call(handler)).body.tasks.length,1);assert.equal((await call(handler,'PATCH',{id:first.body.task.id,version:9,task:{title:'Wrong'}})).statusCode,409);assert.equal((await call(handler,'POST','{bad')).statusCode,400);assert.equal((await call(handler,'POST',{}, {'content-type':'text/plain'})).statusCode,415);assert.equal((await call(handler,'DELETE')).statusCode,405);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('local login rate limit persists across restart',()=>{const dir=temporary();let store=openStore(dir);try{for(let i=0;i<10;i++)assert.equal(store.allowLogin(),true);assert.equal(store.allowLogin(),false);store.close();store=openStore(dir);assert.equal(store.allowLogin(),false);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
